name: Deploy to Google Apps Script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install clasp
      run: npm install -g @google/clasp
      
    - name: Setup clasp credentials
      run: |
        echo "$CLASPRC" > ~/.clasprc.json
      env:
        CLASPRC: ${{ secrets.CLASPRC }}
        
    - name: Deploy to Google Apps Script
      run: clasp push && clasp deploy --description "Mangpong Delivery App v1.0"